apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: qa
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: ghcr.io/belf-kr/basic-mysql-5.7.16:v0.1.0
          name: mysql
          command:
            # 한글과 이모지 입력을 위하여 기본 문자셋 인코딩 변경
            - mysqld
            - --user=mysql
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: qa-config
                  key: mysql-root-password
          ports:
            - containerPort: 3306
              name: mysql
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
            limits:
              cpu: 100m
              memory: 300Mi
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: qa-mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: qa
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-lb
  namespace: qa
spec:
  type: LoadBalancer
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: mysql
