apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qa-mysql-pv-claim
  namespace: qa
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: belf-azurefiles
  resources:
    requests:
      storage: 5Gi
