apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-world-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: 'true'
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - hello-world-ingress.e654a42ba97247c3a6cb.koreacentral.aksapp.io
      secretName: tls-secret
  rules:
    - host: hello-world-ingress.e654a42ba97247c3a6cb.koreacentral.aksapp.io
      http:
        paths:
          - backend:
              serviceName: aks-helloworld-one
              servicePort: 80
            path: /hello-world-one(/|$)(.*)
          - backend:
              serviceName: aks-helloworld-two
              servicePort: 80
            path: /hello-world-two(/|$)(.*)
          - backend:
              serviceName: aks-helloworld-one
              servicePort: 80
            path: /(.*)
