apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: prod
spec:
  selector:
    matchLabels:
      app: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: redis:6.2.4-alpine
          name: redis
          command:
            - redis-server
            - "/redis-master/redis.conf"
          env:
            - name: MASTER
              value: "true"
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 50Mi
          volumeMounts:
            - name: redis-persistent-storage
              mountPath: /data
            - name: config
              mountPath: /redis-master
      volumes:
        - name: redis-persistent-storage
          persistentVolumeClaim:
            claimName: prod-redis-pv-claim
        - name: config
          configMap:
            name: prod-config
            items:
              - key: redis-config
                path: redis.conf
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: prod
spec:
  ports:
    - port: 6379
  selector:
    app: redis
  clusterIP: None
