apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prod-redis-pv-claim
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: belf-azurefiles
  resources:
    requests:
      storage: 1Gi
